Update lambda-versioning-deployment.yml

diff --git a/.github/workflows/lambda-versioning-deployment.yml b/.github/workflows/lambda-versioning-deployment.yml
--- a/.github/workflows/lambda-versioning-deployment.yml
+++ b/.github/workflows/lambda-versioning-deployment.yml
@@ -29,6 +29,13 @@ jobs:
         id: changed-files
         uses: tj-actions/changed-files@v39
 
+      - name: Get the current branch name
+        id: get-branch
+        run: |
+          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+          echo "Current branch: $CURRENT_BRANCH"
+          echo "::set-output name=branch::$CURRENT_BRANCH"
+
       - name: Filter Changed Files
         id: filter-changed-files
         run: |
@@ -44,7 +51,11 @@ jobs:
             updated_dir=$(echo "$mod_dir" | cut -d/ -f1)
             echo "$updated_dir" >> updated_directories.txt
           done
+          echo "Below directories have been updated ..."
+          cat updated_directories.txt
+          echo "Below unique directories were updated ..."
           sort updated_directories.txt | uniq > unique_updated_directories.txt
+          cat unique_updated_directories.txt
           echo "::set-output name=changed_dirs::$(cat unique_updated_directories.txt)"
 
       - name: Zip Lambda Function Code
@@ -91,30 +102,10 @@ jobs:
 
       - name: Upload Lambda Versions to S3
         run: |
-          aws s3 cp lambda_versions.json s3://lambda-versioning-data/lambda_versions.json
-
-  track_lambda_versions:
-    name: Track Lambda Versions
-    runs-on: ubuntu-latest
-    needs: detect_and_publish
-    steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Retrieve and Log Lambda Versions
-        run: |
-          echo "Tracking Lambda versions..."
-          for folder in $(cat unique_updated_directories.txt); do
-            version=$(aws lambda list-versions-by-function --function-name "$folder" --query 'Versions[-1].Version' --output text)
-            echo "Lambda function $folder is now at version $version"
-            jq --arg name "$folder" --arg version "$version" \
-              '.[$name].version = $version' lambda_versions.json > tmp.json && mv tmp.json lambda_versions.json
-          done
-
-      - name: Upload Updated Lambda Versions to S3
-        run: |
-          aws s3 cp lambda_versions.json s3://lambda-versioning-data/lambda_versions.json
+          if [ -f lambda_versions.json ]; then
+            echo "Uploading lambda_versions.json to S3..."
+            aws s3 cp lambda_versions.json s3://lambda-versioning-data/lambda_versions.json
+          else
+            echo "Error: lambda_versions.json does not exist."
+            exit 1
+          fi
