Update lambda-versioning-deployment.yml

diff --git a/.github/workflows/lambda-versioning-deployment.yml b/.github/workflows/lambda-versioning-deployment.yml
--- a/.github/workflows/lambda-versioning-deployment.yml
+++ b/.github/workflows/lambda-versioning-deployment.yml
@@ -113,7 +113,6 @@ jobs:
             NEW_VERSION=$(aws lambda list-versions-by-function --function-name "$folder" --query 'Versions[-1].Version' --output text)
             aws lambda update-alias --function-name "$folder" --name "blue" --function-version "$NEW_VERSION"
           done
-
   track_lambda_versions:
     name: Track Lambda Versions
     runs-on: ubuntu-latest
@@ -141,3 +140,14 @@ jobs:
           done
           echo "Contents of $output_file:"
           cat $output_file
+
+      - name: Upload Lambda Versions Output to S3
+        run: |
+          if [ -f lambda_versions.txt ]; then
+            aws s3 cp lambda_versions.txt s3://lambda-versioning-data/lambda_versions.txt
+          else
+            echo "Error: lambda_versions.txt does not exist."
+            exit 1
+          fi
+ 
+        
